language: vim
dist: bionic

env:
  matrix:
    - CI_TARGET=vim
    - CI_TARGET=neovim VSPEC_VIM=nvim


before_install: |
  if [ "$CI_TARGET" = vim ]; then
    sudo apt-get -y install vim-gnome
  else
    eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
  fi

install:
  - make test-dependencies

script:
  - make tests
